---
jobs:
- name: build-homework-docker-image
  public: true
  serial: true
  plan:
  - get: homework-docker-image-repo
    trigger: true
  - put: docker-image
    params:
      build: homework-docker-image-repo

resources:

- name: homework-docker-image-repo
  type: git
  source:
    uri: https://git.high.am/danhigham/homework.git
    skip_ssl_verification: true
    branch: master

- name: docker-image
  type: docker-image
  source:
    username: {{harbor-username}}
    password: {{harbor-password}}
    repository: {{harbor-repo}}
